package com.cg.bo.enums;

public enum EventType {
    LIVE_PRODUCT_ADDED, USER_METADATA_UPDATED, POST_DELETE, NEW_FOLLOWER, NEW_FOLLOWING, MATCH, DELETE_FOLLOWER, DELETE_FOLLOWING, NEW_SWIPE, UPDATE_MATCH_OR_LIKE_COUNT,LIKE

}
